# This configuration tells LiteLLM to act as a pass-through proxy
# for any model it receives. It will forward the request to the
# OLLAMA_BASE_URL defined in the .env file.

# Enable cost tracking and monitoring
litellm_settings:
  store_model_in_db: true
  track_cost_per_request: true

model_list:
  # Route any request for an Ollama model (prefixed as "ollama/<model>") to the local Ollama server
  - model_name: "ollama/*"
    litellm_params:
      model: "ollama/*"
      api_base: os.environ/OLLAMA_BASE_URL

  # OpenAI models - specific mappings
  - model_name: "gpt-4o-mini"
    litellm_params:
      model: "gpt-4o-mini"
      api_key: os.environ/OPENAI_API_KEY

  - model_name: "gpt-4o"
    litellm_params:
      model: "gpt-4o"
      api_key: os.environ/OPENAI_API_KEY

  # OpenAI models (general pattern)
  - model_name: "gpt-*"
    litellm_params:
      model: "openai/*"
      api_key: os.environ/OPENAI_API_KEY

  # Azure OpenAI - route any model starting with 'azure/' to Azure
  - model_name: "azure/*"
    litellm_params:
      model: "azure/*"         # expects 'azure/<deployment_name>' as the model string
      api_base: os.environ/AZURE_OPENAI_API_BASE
      api_version: os.environ/AZURE_OPENAI_API_VERSION
      api_key: os.environ/AZURE_OPENAI_API_KEY

  # Azure OpenAI - friendly alias for your GPT-5 deployment
  - model_name: "azure-gpt5"
    litellm_params:
      model: "azure/gpt-5-3"   # deployment name
      api_base: os.environ/AZURE_OPENAI_API_BASE
      api_version: os.environ/AZURE_OPENAI_API_VERSION
      api_key: os.environ/AZURE_OPENAI_API_KEY

  # Gemini
  - model_name: "gemini-*"
    litellm_params:
      model: "gemini/*"
      api_key: os.environ/GEMINI_API_KEY

  # Common alias
  - model_name: "gemini-2.5-pro"
    litellm_params:
      model: "gemini/gemini-2.5-pro"
      api_key: os.environ/GEMINI_API_KEY

  # Anthropic (Opus)
  - model_name: "claude-*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY

  # Common alias
  - model_name: "claude-opus-4-1-20250805"
    litellm_params:
      model: "anthropic/claude-opus-4-1-20250805"
      api_key: os.environ/ANTHROPIC_API_KEY

  # xAI (Grok)
  # - model_name: "grok-*"
  #   litellm_params:
  #     model: "xai/*"
  #     api_key: os.environ/XAI_API_KEY

  # # Common alias (rename to the exact xAI model you want)
  # - model_name: "grok-4"
  #   litellm_params:
  #     model: "xai/grok-4"
  #     api_key: os.environ/XAI_API_KEY

  # Fallback to OpenAI provider for any unknown model pattern
  - model_name: "*"
    litellm_params:
      model: "openai/*"
